FROM node:18 AS build-stage
ENV NODE_ENV=development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.development .env.production
RUN npm run build

FROM nginx:alpine AS production-stage

WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/dist .

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
