services:
  base:
    image: docker:dind
    container_name: ctf-base
    privileged: true
    ports:
      - "80:80"
      - "22:22"
      - "8000:8000"
    volumes:
      - ./:/app
      - docker-data:/var/lib/docker
      - challenge/final-flag:root

    entrypoint: ["/app/challenge/start-dind.sh"]

volumes:
  docker-data: